### PR TITLE
Update F series write possibilties

### PR DESCRIPTION
**Pull request by gmcmicken**
Add byte 6 and 8 for heating specific target temp and fan speed, allow fan speed values in range. Tested on FTQ-PB

### CODE REVIEW

**Comment by Arnold-n** [comment]
Thanks! Does your system support any other fanmodes than 0x11, 0x31, or 0x51? If not, I would suggest to make a different change in line 556, to ((wr_val & 0x9F) != 0x11) || ((wr_val & 0x60)  == 0x60).

**Comment by gmcmicken** [comment]
> Thanks! Does your system support any other fanmodes than 0x11, 0x31, or 0x51? If not, I would suggest to make a different change in line 556, to ((wr_val & 0x9F) != 0x11) || ((wr_val & 0x60) == 0x60).

Yes it supports the range from 0x11 to 0x51, but no higher or lower, the increment I'm not totally sure but if you send something unsupported it just goes to a proper value anyway. The BRC remote shows approximate level if you set it to something outside of the set three levels (ie somewhere between medium and high is considered medium on the display)

**Comment by Arnold-n** [comment]
> Yes it supports the range from 0x11 to 0x51, but no higher or lower, the increment I'm not totally sure but if you send something unsupported it just goes to a proper value anyway. The BRC remote shows approximate level if you set it to something outside of the set three levels (ie somewhere between medium and high is considered medium on the display)

Would be surprised if it would really deliver you more than 3 modes low/medium/high; actually I think that fan speed is encoded in bits 5-6 only and that bits 0-4 are usually 1001 (0x11) but given that we haven't seen any other values for these bits, we do not know what they encode. So I would expect 0x12-0x1F to map to low, 0x20-0x3F to medium, and 0x40-0x51 to high. On the other hand, if any 0x12-0x1F would be shown as medium on your BRC, my assumption is likely wrong, as these do have the same zero bit values in bits 5-6 as 0x11.

**Comment by gmcmicken** [comment]
If I set say 0x37, the status retained and reported in packet type 10 is now 0x37 (decimal 55) and I think I can hear the fan change...

**Comment by gmcmicken** [comment]
I can more thoroughly test later, but in regards to the PR I don't think it matters as the range is good enough to restrict write possibility. The controller is fine with non preset values, or does it's own mapping with an expected result.

**Comment by Arnold-n** [comment]
That would be interesting. Perhaps it is not strict enough but if so, that can be resolved later.

**Pull request merged**
